### PR TITLE
Add various key combination with modifiers

### PR DESCRIPTION
**Pull request by ABorgna**
Map [a..z] + modifiers, needed for i3.

### CODE REVIEW

**Comment by miguemely** [comment]
Valid Syntax - Waiting for approval...

**Comment by ghyde** [comment]
:+1:

**Comment by ABorgna** [comment]
As @yamamushi said on yamamushi/twitch-master#18 some alt and ctrl
combination are swapped.

`"alt-x": "alt-sendkey x"` should be `"alt-x": "sendkey alt-x"`

**Comment by niemal** [comment]
Alright, merging and I will push a fix on this commit (style+combination swap).

**Pull request merged**
