### PR TITLE
Fix qemu channel and send commands

### PR DESCRIPTION
**Pull request by francois2metz**
I tried to run it on my machine. It wasn't working because of the channel used to talk to qemu was wrong and the commands sent to qemu wasn't ended with enter.

I guess you already fixed that on your local instance. This is for futur contributors ;)

### CODE REVIEW

**Comment by greenbigfrog** [comment]
I was searching a long time why twitch-master would not communicate with the qemu-process...

Thanks!

To the Repo owner: If you want other people to help improve this you should keep the code up to date (runnable)!

**Comment by francois2metz** [comment]
I was confused too. Did you tried to use this patch?

**Comment by niemal** [comment]
The thing with this issue is that the channel name has somehow changed and varies upon the version.
The streaming machine running qemu is version 2.0.0 while you (and I) are using (presumably) the latest one, since we are using arch linux: 2.4.0.1-1.

I am working on a large-scale fix so everything can be compatible (maybe a dev mode), much thanks for reporting this.

**Comment by francois2metz** [comment]
It doesn't seems to be related to the qemu version. Isn't it? The channel is used in the file `qemu.js`. I'm quite confused.

**Comment by niemal** [comment]
Damn it, I missed that line, sorry I failed miserably -- as you can tell I thought this was a qemu built-in... Someone changed the channel in the twitch fork (the old repo), the qemu.js is different on the running machine...

My apologies, merging.

**Pull request merged**
